// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IPAddressMode = { "type": "teamNumber" } | { "type": "mDNS" } | { "type": "localhost" } | { "type": "custom", "value": string };
