// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IPAddressMode } from "./IPAddressMode";

export type NetworkSettingsUpdateMessage = { ipAddressMode: IPAddressMode, teamNumber: number, };
